on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'folderaccess-check'  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: .             # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1

    - name: dotnet publish
      run: dotnet publish # -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
       app-name: ${{ env.AZURE_WEBAPP_NAME }}
       publish-profile: ${{ secrets.AzureAppService_PublishProfile_22823d8812bd491b9ca52d833ec87d30 }}
       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
